/**
 *
 *  AiContext.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */
#include "pch.h"
#include "AiContext.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string AiContext::Cols::_message_id = "message_id";
const std::string AiContext::Cols::_thread_id = "thread_id";
const std::string AiContext::Cols::_role = "role";
const std::string AiContext::Cols::_content = "content";
const std::string AiContext::Cols::_attachment = "attachment";
const std::string AiContext::Cols::_reasoning_content = "reasoning_content";
const std::string AiContext::Cols::_created_time = "created_time";
const std::string AiContext::primaryKeyName = "message_id";
const bool AiContext::hasPrimaryKey = true;
const std::string AiContext::tableName = "ai_context";

const std::vector<typename AiContext::MetaData> AiContext::metaData_={
{"message_id","std::string","text",0,0,1,0},
{"thread_id","int64_t","integer",8,0,0,1},
{"role","std::string","text",0,0,0,1},
{"content","std::string","text",0,0,0,1},
{"attachment","std::string","text",0,0,0,0},
{"reasoning_content","std::string","text",0,0,0,0},
{"created_time","int64_t","integer",8,0,0,0}
};
const std::string &AiContext::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
AiContext::AiContext(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["message_id"].isNull())
        {
            messageId_=std::make_shared<std::string>(r["message_id"].as<std::string>());
        }
        if(!r["thread_id"].isNull())
        {
            threadId_=std::make_shared<int64_t>(r["thread_id"].as<int64_t>());
        }
        if(!r["role"].isNull())
        {
            role_=std::make_shared<std::string>(r["role"].as<std::string>());
        }
        if(!r["content"].isNull())
        {
            content_=std::make_shared<std::string>(r["content"].as<std::string>());
        }
        if(!r["attachment"].isNull())
        {
            attachment_=std::make_shared<std::string>(r["attachment"].as<std::string>());
        }
        if(!r["reasoning_content"].isNull())
        {
            reasoningContent_=std::make_shared<std::string>(r["reasoning_content"].as<std::string>());
        }
        if(!r["created_time"].isNull())
        {
            createdTime_=std::make_shared<int64_t>(r["created_time"].as<int64_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            messageId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            threadId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            role_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            content_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            attachment_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            reasoningContent_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            createdTime_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
    }

}

AiContext::AiContext(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            messageId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            threadId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            role_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            content_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            attachment_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            reasoningContent_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            createdTime_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
}

AiContext::AiContext(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("message_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["message_id"].isNull())
        {
            messageId_=std::make_shared<std::string>(pJson["message_id"].asString());
        }
    }
    if(pJson.isMember("thread_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["thread_id"].isNull())
        {
            threadId_=std::make_shared<int64_t>((int64_t)pJson["thread_id"].asInt64());
        }
    }
    if(pJson.isMember("role"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["role"].isNull())
        {
            role_=std::make_shared<std::string>(pJson["role"].asString());
        }
    }
    if(pJson.isMember("content"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["content"].isNull())
        {
            content_=std::make_shared<std::string>(pJson["content"].asString());
        }
    }
    if(pJson.isMember("attachment"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["attachment"].isNull())
        {
            attachment_=std::make_shared<std::string>(pJson["attachment"].asString());
        }
    }
    if(pJson.isMember("reasoning_content"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["reasoning_content"].isNull())
        {
            reasoningContent_=std::make_shared<std::string>(pJson["reasoning_content"].asString());
        }
    }
    if(pJson.isMember("created_time"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["created_time"].isNull())
        {
            createdTime_=std::make_shared<int64_t>((int64_t)pJson["created_time"].asInt64());
        }
    }
}

void AiContext::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            messageId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            threadId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            role_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            content_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            attachment_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            reasoningContent_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            createdTime_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
}

void AiContext::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("message_id"))
    {
        if(!pJson["message_id"].isNull())
        {
            messageId_=std::make_shared<std::string>(pJson["message_id"].asString());
        }
    }
    if(pJson.isMember("thread_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["thread_id"].isNull())
        {
            threadId_=std::make_shared<int64_t>((int64_t)pJson["thread_id"].asInt64());
        }
    }
    if(pJson.isMember("role"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["role"].isNull())
        {
            role_=std::make_shared<std::string>(pJson["role"].asString());
        }
    }
    if(pJson.isMember("content"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["content"].isNull())
        {
            content_=std::make_shared<std::string>(pJson["content"].asString());
        }
    }
    if(pJson.isMember("attachment"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["attachment"].isNull())
        {
            attachment_=std::make_shared<std::string>(pJson["attachment"].asString());
        }
    }
    if(pJson.isMember("reasoning_content"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["reasoning_content"].isNull())
        {
            reasoningContent_=std::make_shared<std::string>(pJson["reasoning_content"].asString());
        }
    }
    if(pJson.isMember("created_time"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["created_time"].isNull())
        {
            createdTime_=std::make_shared<int64_t>((int64_t)pJson["created_time"].asInt64());
        }
    }
}

const std::string &AiContext::getValueOfMessageId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(messageId_)
        return *messageId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AiContext::getMessageId() const noexcept
{
    return messageId_;
}
void AiContext::setMessageId(const std::string &pMessageId) noexcept
{
    messageId_ = std::make_shared<std::string>(pMessageId);
    dirtyFlag_[0] = true;
}
void AiContext::setMessageId(std::string &&pMessageId) noexcept
{
    messageId_ = std::make_shared<std::string>(std::move(pMessageId));
    dirtyFlag_[0] = true;
}
void AiContext::setMessageIdToNull() noexcept
{
    messageId_.reset();
    dirtyFlag_[0] = true;
}
const typename AiContext::PrimaryKeyType & AiContext::getPrimaryKey() const
{
    assert(messageId_);
    return *messageId_;
}

const int64_t &AiContext::getValueOfThreadId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(threadId_)
        return *threadId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &AiContext::getThreadId() const noexcept
{
    return threadId_;
}
void AiContext::setThreadId(const int64_t &pThreadId) noexcept
{
    threadId_ = std::make_shared<int64_t>(pThreadId);
    dirtyFlag_[1] = true;
}

const std::string &AiContext::getValueOfRole() const noexcept
{
    static const std::string defaultValue = std::string();
    if(role_)
        return *role_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AiContext::getRole() const noexcept
{
    return role_;
}
void AiContext::setRole(const std::string &pRole) noexcept
{
    role_ = std::make_shared<std::string>(pRole);
    dirtyFlag_[2] = true;
}
void AiContext::setRole(std::string &&pRole) noexcept
{
    role_ = std::make_shared<std::string>(std::move(pRole));
    dirtyFlag_[2] = true;
}

const std::string &AiContext::getValueOfContent() const noexcept
{
    static const std::string defaultValue = std::string();
    if(content_)
        return *content_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AiContext::getContent() const noexcept
{
    return content_;
}
void AiContext::setContent(const std::string &pContent) noexcept
{
    content_ = std::make_shared<std::string>(pContent);
    dirtyFlag_[3] = true;
}
void AiContext::setContent(std::string &&pContent) noexcept
{
    content_ = std::make_shared<std::string>(std::move(pContent));
    dirtyFlag_[3] = true;
}

const std::string &AiContext::getValueOfAttachment() const noexcept
{
    static const std::string defaultValue = std::string();
    if(attachment_)
        return *attachment_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AiContext::getAttachment() const noexcept
{
    return attachment_;
}
void AiContext::setAttachment(const std::string &pAttachment) noexcept
{
    attachment_ = std::make_shared<std::string>(pAttachment);
    dirtyFlag_[4] = true;
}
void AiContext::setAttachment(std::string &&pAttachment) noexcept
{
    attachment_ = std::make_shared<std::string>(std::move(pAttachment));
    dirtyFlag_[4] = true;
}
void AiContext::setAttachmentToNull() noexcept
{
    attachment_.reset();
    dirtyFlag_[4] = true;
}

const std::string &AiContext::getValueOfReasoningContent() const noexcept
{
    static const std::string defaultValue = std::string();
    if(reasoningContent_)
        return *reasoningContent_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AiContext::getReasoningContent() const noexcept
{
    return reasoningContent_;
}
void AiContext::setReasoningContent(const std::string &pReasoningContent) noexcept
{
    reasoningContent_ = std::make_shared<std::string>(pReasoningContent);
    dirtyFlag_[5] = true;
}
void AiContext::setReasoningContent(std::string &&pReasoningContent) noexcept
{
    reasoningContent_ = std::make_shared<std::string>(std::move(pReasoningContent));
    dirtyFlag_[5] = true;
}
void AiContext::setReasoningContentToNull() noexcept
{
    reasoningContent_.reset();
    dirtyFlag_[5] = true;
}

const int64_t &AiContext::getValueOfCreatedTime() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(createdTime_)
        return *createdTime_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &AiContext::getCreatedTime() const noexcept
{
    return createdTime_;
}
void AiContext::setCreatedTime(const int64_t &pCreatedTime) noexcept
{
    createdTime_ = std::make_shared<int64_t>(pCreatedTime);
    dirtyFlag_[6] = true;
}
void AiContext::setCreatedTimeToNull() noexcept
{
    createdTime_.reset();
    dirtyFlag_[6] = true;
}

void AiContext::updateId(const uint64_t id)
{
}

const std::vector<std::string> &AiContext::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "message_id",
        "thread_id",
        "role",
        "content",
        "attachment",
        "reasoning_content",
        "created_time"
    };
    return inCols;
}

void AiContext::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getMessageId())
        {
            binder << getValueOfMessageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getThreadId())
        {
            binder << getValueOfThreadId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRole())
        {
            binder << getValueOfRole();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getContent())
        {
            binder << getValueOfContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAttachment())
        {
            binder << getValueOfAttachment();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getReasoningContent())
        {
            binder << getValueOfReasoningContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedTime())
        {
            binder << getValueOfCreatedTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> AiContext::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void AiContext::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getMessageId())
        {
            binder << getValueOfMessageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getThreadId())
        {
            binder << getValueOfThreadId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRole())
        {
            binder << getValueOfRole();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getContent())
        {
            binder << getValueOfContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAttachment())
        {
            binder << getValueOfAttachment();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getReasoningContent())
        {
            binder << getValueOfReasoningContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedTime())
        {
            binder << getValueOfCreatedTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value AiContext::toJson() const
{
    Json::Value ret;
    if(getMessageId())
    {
        ret["message_id"]=getValueOfMessageId();
    }
    else
    {
        ret["message_id"]=Json::Value();
    }
    if(getThreadId())
    {
        ret["thread_id"]=(Json::Int64)getValueOfThreadId();
    }
    else
    {
        ret["thread_id"]=Json::Value();
    }
    if(getRole())
    {
        ret["role"]=getValueOfRole();
    }
    else
    {
        ret["role"]=Json::Value();
    }
    if(getContent())
    {
        ret["content"]=getValueOfContent();
    }
    else
    {
        ret["content"]=Json::Value();
    }
    if(getAttachment())
    {
        ret["attachment"]=getValueOfAttachment();
    }
    else
    {
        ret["attachment"]=Json::Value();
    }
    if(getReasoningContent())
    {
        ret["reasoning_content"]=getValueOfReasoningContent();
    }
    else
    {
        ret["reasoning_content"]=Json::Value();
    }
    if(getCreatedTime())
    {
        ret["created_time"]=(Json::Int64)getValueOfCreatedTime();
    }
    else
    {
        ret["created_time"]=Json::Value();
    }
    return ret;
}

Json::Value AiContext::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getMessageId())
            {
                ret[pMasqueradingVector[0]]=getValueOfMessageId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getThreadId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfThreadId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getRole())
            {
                ret[pMasqueradingVector[2]]=getValueOfRole();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getContent())
            {
                ret[pMasqueradingVector[3]]=getValueOfContent();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getAttachment())
            {
                ret[pMasqueradingVector[4]]=getValueOfAttachment();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getReasoningContent())
            {
                ret[pMasqueradingVector[5]]=getValueOfReasoningContent();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCreatedTime())
            {
                ret[pMasqueradingVector[6]]=(Json::Int64)getValueOfCreatedTime();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getMessageId())
    {
        ret["message_id"]=getValueOfMessageId();
    }
    else
    {
        ret["message_id"]=Json::Value();
    }
    if(getThreadId())
    {
        ret["thread_id"]=(Json::Int64)getValueOfThreadId();
    }
    else
    {
        ret["thread_id"]=Json::Value();
    }
    if(getRole())
    {
        ret["role"]=getValueOfRole();
    }
    else
    {
        ret["role"]=Json::Value();
    }
    if(getContent())
    {
        ret["content"]=getValueOfContent();
    }
    else
    {
        ret["content"]=Json::Value();
    }
    if(getAttachment())
    {
        ret["attachment"]=getValueOfAttachment();
    }
    else
    {
        ret["attachment"]=Json::Value();
    }
    if(getReasoningContent())
    {
        ret["reasoning_content"]=getValueOfReasoningContent();
    }
    else
    {
        ret["reasoning_content"]=Json::Value();
    }
    if(getCreatedTime())
    {
        ret["created_time"]=(Json::Int64)getValueOfCreatedTime();
    }
    else
    {
        ret["created_time"]=Json::Value();
    }
    return ret;
}

bool AiContext::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("message_id"))
    {
        if(!validJsonOfField(0, "message_id", pJson["message_id"], err, true))
            return false;
    }
    if(pJson.isMember("thread_id"))
    {
        if(!validJsonOfField(1, "thread_id", pJson["thread_id"], err, true))
            return false;
    }
    else
    {
        err="The thread_id column cannot be null";
        return false;
    }
    if(pJson.isMember("role"))
    {
        if(!validJsonOfField(2, "role", pJson["role"], err, true))
            return false;
    }
    else
    {
        err="The role column cannot be null";
        return false;
    }
    if(pJson.isMember("content"))
    {
        if(!validJsonOfField(3, "content", pJson["content"], err, true))
            return false;
    }
    else
    {
        err="The content column cannot be null";
        return false;
    }
    if(pJson.isMember("attachment"))
    {
        if(!validJsonOfField(4, "attachment", pJson["attachment"], err, true))
            return false;
    }
    if(pJson.isMember("reasoning_content"))
    {
        if(!validJsonOfField(5, "reasoning_content", pJson["reasoning_content"], err, true))
            return false;
    }
    if(pJson.isMember("created_time"))
    {
        if(!validJsonOfField(6, "created_time", pJson["created_time"], err, true))
            return false;
    }
    return true;
}
bool AiContext::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AiContext::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("message_id"))
    {
        if(!validJsonOfField(0, "message_id", pJson["message_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("thread_id"))
    {
        if(!validJsonOfField(1, "thread_id", pJson["thread_id"], err, false))
            return false;
    }
    if(pJson.isMember("role"))
    {
        if(!validJsonOfField(2, "role", pJson["role"], err, false))
            return false;
    }
    if(pJson.isMember("content"))
    {
        if(!validJsonOfField(3, "content", pJson["content"], err, false))
            return false;
    }
    if(pJson.isMember("attachment"))
    {
        if(!validJsonOfField(4, "attachment", pJson["attachment"], err, false))
            return false;
    }
    if(pJson.isMember("reasoning_content"))
    {
        if(!validJsonOfField(5, "reasoning_content", pJson["reasoning_content"], err, false))
            return false;
    }
    if(pJson.isMember("created_time"))
    {
        if(!validJsonOfField(6, "created_time", pJson["created_time"], err, false))
            return false;
    }
    return true;
}
bool AiContext::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AiContext::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
