/**
 *
 *  Block.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */
#include "pch.h"

#include "Block.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Block::primaryKeyName = "";
const bool Block::hasPrimaryKey = false;
const std::string Block::tableName = "block";

const std::vector<typename Block::MetaData> Block::metaData_={
};
const std::string &Block::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Block::Block(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 0 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
    }

}

Block::Block(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

Block::Block(const Json::Value &pJson) noexcept(false)
{
}

void Block::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

void Block::updateByJson(const Json::Value &pJson) noexcept(false)
{
}

void Block::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Block::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
    };
    return inCols;
}

void Block::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
}

const std::vector<std::string> Block::updateColumns() const
{
    std::vector<std::string> ret;
    return ret;
}

void Block::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
}
Json::Value Block::toJson() const
{
    Json::Value ret;
    return ret;
}

Json::Value Block::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 0)
    {
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    return ret;
}

bool Block::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Block::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Block::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Block::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Block::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
