/**
 *
 *  Groups.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */
#include "pch.h"
#include "Groups.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Groups::Cols::_group_id = "group_id";
const std::string Groups::Cols::_group_name = "group_name";
const std::string Groups::Cols::_master_uid = "master_uid";
const std::string Groups::Cols::_group_avatar = "group_avatar";
const std::string Groups::Cols::_description = "description";
const std::string Groups::Cols::_create_time = "create_time";
const std::string Groups::primaryKeyName = "group_id";
const bool Groups::hasPrimaryKey = true;
const std::string Groups::tableName = "groups";

const std::vector<typename Groups::MetaData> Groups::metaData_={
{"group_id","std::string","text",0,0,1,0},
{"group_name","std::string","text",0,0,0,1},
{"master_uid","std::string","text",0,0,0,1},
{"group_avatar","std::string","text",0,0,0,0},
{"description","std::string","text",0,0,0,0},
{"create_time","std::string","timestamp",0,0,0,0}
};
const std::string &Groups::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Groups::Groups(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["group_id"].isNull())
        {
            groupId_=std::make_shared<std::string>(r["group_id"].as<std::string>());
        }
        if(!r["group_name"].isNull())
        {
            groupName_=std::make_shared<std::string>(r["group_name"].as<std::string>());
        }
        if(!r["master_uid"].isNull())
        {
            masterUid_=std::make_shared<std::string>(r["master_uid"].as<std::string>());
        }
        if(!r["group_avatar"].isNull())
        {
            groupAvatar_=std::make_shared<std::string>(r["group_avatar"].as<std::string>());
        }
        if(!r["description"].isNull())
        {
            description_=std::make_shared<std::string>(r["description"].as<std::string>());
        }
        if(!r["create_time"].isNull())
        {
            auto timeStr = r["create_time"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTime_=std::make_shared<std::string>(timeStr);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            groupId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            groupName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            masterUid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            groupAvatar_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            description_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTime_=std::make_shared<std::string>(timeStr);
            }
        }
    }

}

Groups::Groups(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            groupId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            groupName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            masterUid_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            groupAvatar_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            createTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

Groups::Groups(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("group_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["group_id"].isNull())
        {
            groupId_=std::make_shared<std::string>(pJson["group_id"].asString());
        }
    }
    if(pJson.isMember("group_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["group_name"].isNull())
        {
            groupName_=std::make_shared<std::string>(pJson["group_name"].asString());
        }
    }
    if(pJson.isMember("master_uid"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["master_uid"].isNull())
        {
            masterUid_=std::make_shared<std::string>(pJson["master_uid"].asString());
        }
    }
    if(pJson.isMember("group_avatar"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["group_avatar"].isNull())
        {
            groupAvatar_=std::make_shared<std::string>(pJson["group_avatar"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("create_time"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["create_time"].isNull())
        {
            createTime_=std::make_shared<std::string>(pJson["create_time"].asString());
        }
    }
}

void Groups::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            groupId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            groupName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            masterUid_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            groupAvatar_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            createTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

void Groups::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("group_id"))
    {
        if(!pJson["group_id"].isNull())
        {
            groupId_=std::make_shared<std::string>(pJson["group_id"].asString());
        }
    }
    if(pJson.isMember("group_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["group_name"].isNull())
        {
            groupName_=std::make_shared<std::string>(pJson["group_name"].asString());
        }
    }
    if(pJson.isMember("master_uid"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["master_uid"].isNull())
        {
            masterUid_=std::make_shared<std::string>(pJson["master_uid"].asString());
        }
    }
    if(pJson.isMember("group_avatar"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["group_avatar"].isNull())
        {
            groupAvatar_=std::make_shared<std::string>(pJson["group_avatar"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("create_time"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["create_time"].isNull())
        {
            createTime_=std::make_shared<std::string>(pJson["create_time"].asString());
        }
    }
}

const std::string &Groups::getValueOfGroupId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(groupId_)
        return *groupId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Groups::getGroupId() const noexcept
{
    return groupId_;
}
void Groups::setGroupId(const std::string &pGroupId) noexcept
{
    groupId_ = std::make_shared<std::string>(pGroupId);
    dirtyFlag_[0] = true;
}
void Groups::setGroupId(std::string &&pGroupId) noexcept
{
    groupId_ = std::make_shared<std::string>(std::move(pGroupId));
    dirtyFlag_[0] = true;
}
void Groups::setGroupIdToNull() noexcept
{
    groupId_.reset();
    dirtyFlag_[0] = true;
}
const typename Groups::PrimaryKeyType & Groups::getPrimaryKey() const
{
    assert(groupId_);
    return *groupId_;
}

const std::string &Groups::getValueOfGroupName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(groupName_)
        return *groupName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Groups::getGroupName() const noexcept
{
    return groupName_;
}
void Groups::setGroupName(const std::string &pGroupName) noexcept
{
    groupName_ = std::make_shared<std::string>(pGroupName);
    dirtyFlag_[1] = true;
}
void Groups::setGroupName(std::string &&pGroupName) noexcept
{
    groupName_ = std::make_shared<std::string>(std::move(pGroupName));
    dirtyFlag_[1] = true;
}

const std::string &Groups::getValueOfMasterUid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(masterUid_)
        return *masterUid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Groups::getMasterUid() const noexcept
{
    return masterUid_;
}
void Groups::setMasterUid(const std::string &pMasterUid) noexcept
{
    masterUid_ = std::make_shared<std::string>(pMasterUid);
    dirtyFlag_[2] = true;
}
void Groups::setMasterUid(std::string &&pMasterUid) noexcept
{
    masterUid_ = std::make_shared<std::string>(std::move(pMasterUid));
    dirtyFlag_[2] = true;
}

const std::string &Groups::getValueOfGroupAvatar() const noexcept
{
    static const std::string defaultValue = std::string();
    if(groupAvatar_)
        return *groupAvatar_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Groups::getGroupAvatar() const noexcept
{
    return groupAvatar_;
}
void Groups::setGroupAvatar(const std::string &pGroupAvatar) noexcept
{
    groupAvatar_ = std::make_shared<std::string>(pGroupAvatar);
    dirtyFlag_[3] = true;
}
void Groups::setGroupAvatar(std::string &&pGroupAvatar) noexcept
{
    groupAvatar_ = std::make_shared<std::string>(std::move(pGroupAvatar));
    dirtyFlag_[3] = true;
}
void Groups::setGroupAvatarToNull() noexcept
{
    groupAvatar_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Groups::getValueOfDescription() const noexcept
{
    static const std::string defaultValue = std::string();
    if(description_)
        return *description_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Groups::getDescription() const noexcept
{
    return description_;
}
void Groups::setDescription(const std::string &pDescription) noexcept
{
    description_ = std::make_shared<std::string>(pDescription);
    dirtyFlag_[4] = true;
}
void Groups::setDescription(std::string &&pDescription) noexcept
{
    description_ = std::make_shared<std::string>(std::move(pDescription));
    dirtyFlag_[4] = true;
}
void Groups::setDescriptionToNull() noexcept
{
    description_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Groups::getValueOfCreateTime() const noexcept
{
    static const std::string defaultValue = std::string();
    if(createTime_)
        return *createTime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Groups::getCreateTime() const noexcept
{
    return createTime_;
}
void Groups::setCreateTime(const std::string &pCreateTime) noexcept
{
    createTime_ = std::make_shared<std::string>(pCreateTime);
    dirtyFlag_[5] = true;
}
void Groups::setCreateTime(std::string &&pCreateTime) noexcept
{
    createTime_ = std::make_shared<std::string>(std::move(pCreateTime));
    dirtyFlag_[5] = true;
}
void Groups::setCreateTimeToNull() noexcept
{
    createTime_.reset();
    dirtyFlag_[5] = true;
}

void Groups::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Groups::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "group_id",
        "group_name",
        "master_uid",
        "group_avatar",
        "description",
        "create_time"
    };
    return inCols;
}

void Groups::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getGroupId())
        {
            binder << getValueOfGroupId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getGroupName())
        {
            binder << getValueOfGroupName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMasterUid())
        {
            binder << getValueOfMasterUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getGroupAvatar())
        {
            binder << getValueOfGroupAvatar();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCreateTime())
        {
            binder << getValueOfCreateTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Groups::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void Groups::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getGroupId())
        {
            binder << getValueOfGroupId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getGroupName())
        {
            binder << getValueOfGroupName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMasterUid())
        {
            binder << getValueOfMasterUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getGroupAvatar())
        {
            binder << getValueOfGroupAvatar();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCreateTime())
        {
            binder << getValueOfCreateTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Groups::toJson() const
{
    Json::Value ret;
    if(getGroupId())
    {
        ret["group_id"]=getValueOfGroupId();
    }
    else
    {
        ret["group_id"]=Json::Value();
    }
    if(getGroupName())
    {
        ret["group_name"]=getValueOfGroupName();
    }
    else
    {
        ret["group_name"]=Json::Value();
    }
    if(getMasterUid())
    {
        ret["master_uid"]=getValueOfMasterUid();
    }
    else
    {
        ret["master_uid"]=Json::Value();
    }
    if(getGroupAvatar())
    {
        ret["group_avatar"]=getValueOfGroupAvatar();
    }
    else
    {
        ret["group_avatar"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getCreateTime())
    {
        ret["create_time"]=getValueOfCreateTime();
    }
    else
    {
        ret["create_time"]=Json::Value();
    }
    return ret;
}

Json::Value Groups::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getGroupId())
            {
                ret[pMasqueradingVector[0]]=getValueOfGroupId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getGroupName())
            {
                ret[pMasqueradingVector[1]]=getValueOfGroupName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getMasterUid())
            {
                ret[pMasqueradingVector[2]]=getValueOfMasterUid();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getGroupAvatar())
            {
                ret[pMasqueradingVector[3]]=getValueOfGroupAvatar();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getDescription())
            {
                ret[pMasqueradingVector[4]]=getValueOfDescription();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getCreateTime())
            {
                ret[pMasqueradingVector[5]]=getValueOfCreateTime();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getGroupId())
    {
        ret["group_id"]=getValueOfGroupId();
    }
    else
    {
        ret["group_id"]=Json::Value();
    }
    if(getGroupName())
    {
        ret["group_name"]=getValueOfGroupName();
    }
    else
    {
        ret["group_name"]=Json::Value();
    }
    if(getMasterUid())
    {
        ret["master_uid"]=getValueOfMasterUid();
    }
    else
    {
        ret["master_uid"]=Json::Value();
    }
    if(getGroupAvatar())
    {
        ret["group_avatar"]=getValueOfGroupAvatar();
    }
    else
    {
        ret["group_avatar"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getCreateTime())
    {
        ret["create_time"]=getValueOfCreateTime();
    }
    else
    {
        ret["create_time"]=Json::Value();
    }
    return ret;
}

bool Groups::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("group_id"))
    {
        if(!validJsonOfField(0, "group_id", pJson["group_id"], err, true))
            return false;
    }
    if(pJson.isMember("group_name"))
    {
        if(!validJsonOfField(1, "group_name", pJson["group_name"], err, true))
            return false;
    }
    else
    {
        err="The group_name column cannot be null";
        return false;
    }
    if(pJson.isMember("master_uid"))
    {
        if(!validJsonOfField(2, "master_uid", pJson["master_uid"], err, true))
            return false;
    }
    else
    {
        err="The master_uid column cannot be null";
        return false;
    }
    if(pJson.isMember("group_avatar"))
    {
        if(!validJsonOfField(3, "group_avatar", pJson["group_avatar"], err, true))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(4, "description", pJson["description"], err, true))
            return false;
    }
    if(pJson.isMember("create_time"))
    {
        if(!validJsonOfField(5, "create_time", pJson["create_time"], err, true))
            return false;
    }
    return true;
}
bool Groups::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Groups::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("group_id"))
    {
        if(!validJsonOfField(0, "group_id", pJson["group_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("group_name"))
    {
        if(!validJsonOfField(1, "group_name", pJson["group_name"], err, false))
            return false;
    }
    if(pJson.isMember("master_uid"))
    {
        if(!validJsonOfField(2, "master_uid", pJson["master_uid"], err, false))
            return false;
    }
    if(pJson.isMember("group_avatar"))
    {
        if(!validJsonOfField(3, "group_avatar", pJson["group_avatar"], err, false))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(4, "description", pJson["description"], err, false))
            return false;
    }
    if(pJson.isMember("create_time"))
    {
        if(!validJsonOfField(5, "create_time", pJson["create_time"], err, false))
            return false;
    }
    return true;
}
bool Groups::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Groups::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson,
                              std::string &err,
                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
