/**
 *
 *  Messages.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */
#include "pch.h"
#include "Messages.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Messages::Cols::_message_id = "message_id";
const std::string Messages::Cols::_thread_id = "thread_id";
const std::string Messages::Cols::_sender_uid = "sender_uid";
const std::string Messages::Cols::_sender_name = "sender_name";
const std::string Messages::Cols::_sender_avatar = "sender_avatar";
const std::string Messages::Cols::_content = "content";
const std::string Messages::Cols::_attachment = "attachment";
const std::string Messages::Cols::_create_time = "create_time";
const std::string Messages::Cols::_update_time = "update_time";
const std::string Messages::primaryKeyName = "message_id";
const bool Messages::hasPrimaryKey = true;
const std::string Messages::tableName = "messages";

const std::vector<typename Messages::MetaData> Messages::metaData_={
{"message_id","int64_t","bigint",8,0,1,0},
{"thread_id","int64_t","integer",8,0,0,1},
{"sender_uid","std::string","text",0,0,0,1},
{"sender_name","std::string","text",0,0,0,1},
{"sender_avatar","std::string","text",0,0,0,1},
{"content","std::string","text",0,0,0,0},
{"attachment","std::string","text",0,0,0,0},
{"create_time","std::string","timestamp",0,0,0,0},
{"update_time","std::string","timestamp",0,0,0,0}
};
const std::string &Messages::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Messages::Messages(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["message_id"].isNull())
        {
            messageId_=std::make_shared<int64_t>(r["message_id"].as<int64_t>());
        }
        if(!r["thread_id"].isNull())
        {
            threadId_=std::make_shared<int64_t>(r["thread_id"].as<int64_t>());
        }
        if(!r["sender_uid"].isNull())
        {
            senderUid_=std::make_shared<std::string>(r["sender_uid"].as<std::string>());
        }
        if(!r["sender_name"].isNull())
        {
            senderName_=std::make_shared<std::string>(r["sender_name"].as<std::string>());
        }
        if(!r["sender_avatar"].isNull())
        {
            senderAvatar_=std::make_shared<std::string>(r["sender_avatar"].as<std::string>());
        }
        if(!r["content"].isNull())
        {
            content_=std::make_shared<std::string>(r["content"].as<std::string>());
        }
        if(!r["attachment"].isNull())
        {
            attachment_=std::make_shared<std::string>(r["attachment"].as<std::string>());
        }
        if(!r["create_time"].isNull())
        {
            auto timeStr = r["create_time"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTime_=std::make_shared<std::string>(timeStr);
            }
        }
        if(!r["update_time"].isNull())
        {
            auto timeStr = r["update_time"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTime_=std::make_shared<std::string>(timeStr);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            messageId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            threadId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            senderUid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            senderName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            senderAvatar_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            content_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            attachment_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTime_=std::make_shared<std::string>(timeStr);
            }
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updateTime_=std::make_shared<std::string>(timeStr);
            }
        }
    }

}

Messages::Messages(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            messageId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            threadId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            senderUid_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            senderName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            senderAvatar_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            content_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            attachment_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            createTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            updateTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}

Messages::Messages(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("message_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["message_id"].isNull())
        {
            messageId_=std::make_shared<int64_t>((int64_t)pJson["message_id"].asInt64());
        }
    }
    if(pJson.isMember("thread_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["thread_id"].isNull())
        {
            threadId_=std::make_shared<int64_t>((int64_t)pJson["thread_id"].asInt64());
        }
    }
    if(pJson.isMember("sender_uid"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["sender_uid"].isNull())
        {
            senderUid_=std::make_shared<std::string>(pJson["sender_uid"].asString());
        }
    }
    if(pJson.isMember("sender_name"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["sender_name"].isNull())
        {
            senderName_=std::make_shared<std::string>(pJson["sender_name"].asString());
        }
    }
    if(pJson.isMember("sender_avatar"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["sender_avatar"].isNull())
        {
            senderAvatar_=std::make_shared<std::string>(pJson["sender_avatar"].asString());
        }
    }
    if(pJson.isMember("content"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["content"].isNull())
        {
            content_=std::make_shared<std::string>(pJson["content"].asString());
        }
    }
    if(pJson.isMember("attachment"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["attachment"].isNull())
        {
            attachment_=std::make_shared<std::string>(pJson["attachment"].asString());
        }
    }
    if(pJson.isMember("create_time"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["create_time"].isNull())
        {
            createTime_=std::make_shared<std::string>(pJson["create_time"].asString());
        }
    }
    if(pJson.isMember("update_time"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["update_time"].isNull())
        {
            updateTime_=std::make_shared<std::string>(pJson["update_time"].asString());
        }
    }
}

void Messages::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            messageId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            threadId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            senderUid_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            senderName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            senderAvatar_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            content_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            attachment_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            createTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            updateTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}

void Messages::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("message_id"))
    {
        if(!pJson["message_id"].isNull())
        {
            messageId_=std::make_shared<int64_t>((int64_t)pJson["message_id"].asInt64());
        }
    }
    if(pJson.isMember("thread_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["thread_id"].isNull())
        {
            threadId_=std::make_shared<int64_t>((int64_t)pJson["thread_id"].asInt64());
        }
    }
    if(pJson.isMember("sender_uid"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["sender_uid"].isNull())
        {
            senderUid_=std::make_shared<std::string>(pJson["sender_uid"].asString());
        }
    }
    if(pJson.isMember("sender_name"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["sender_name"].isNull())
        {
            senderName_=std::make_shared<std::string>(pJson["sender_name"].asString());
        }
    }
    if(pJson.isMember("sender_avatar"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["sender_avatar"].isNull())
        {
            senderAvatar_=std::make_shared<std::string>(pJson["sender_avatar"].asString());
        }
    }
    if(pJson.isMember("content"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["content"].isNull())
        {
            content_=std::make_shared<std::string>(pJson["content"].asString());
        }
    }
    if(pJson.isMember("attachment"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["attachment"].isNull())
        {
            attachment_=std::make_shared<std::string>(pJson["attachment"].asString());
        }
    }
    if(pJson.isMember("create_time"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["create_time"].isNull())
        {
            createTime_=std::make_shared<std::string>(pJson["create_time"].asString());
        }
    }
    if(pJson.isMember("update_time"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["update_time"].isNull())
        {
            updateTime_=std::make_shared<std::string>(pJson["update_time"].asString());
        }
    }
}

const int64_t &Messages::getValueOfMessageId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(messageId_)
        return *messageId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Messages::getMessageId() const noexcept
{
    return messageId_;
}
void Messages::setMessageId(const int64_t &pMessageId) noexcept
{
    messageId_ = std::make_shared<int64_t>(pMessageId);
    dirtyFlag_[0] = true;
}
void Messages::setMessageIdToNull() noexcept
{
    messageId_.reset();
    dirtyFlag_[0] = true;
}
const typename Messages::PrimaryKeyType & Messages::getPrimaryKey() const
{
    assert(messageId_);
    return *messageId_;
}

const int64_t &Messages::getValueOfThreadId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(threadId_)
        return *threadId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Messages::getThreadId() const noexcept
{
    return threadId_;
}
void Messages::setThreadId(const int64_t &pThreadId) noexcept
{
    threadId_ = std::make_shared<int64_t>(pThreadId);
    dirtyFlag_[1] = true;
}

const std::string &Messages::getValueOfSenderUid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(senderUid_)
        return *senderUid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Messages::getSenderUid() const noexcept
{
    return senderUid_;
}
void Messages::setSenderUid(const std::string &pSenderUid) noexcept
{
    senderUid_ = std::make_shared<std::string>(pSenderUid);
    dirtyFlag_[2] = true;
}
void Messages::setSenderUid(std::string &&pSenderUid) noexcept
{
    senderUid_ = std::make_shared<std::string>(std::move(pSenderUid));
    dirtyFlag_[2] = true;
}

const std::string &Messages::getValueOfSenderName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(senderName_)
        return *senderName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Messages::getSenderName() const noexcept
{
    return senderName_;
}
void Messages::setSenderName(const std::string &pSenderName) noexcept
{
    senderName_ = std::make_shared<std::string>(pSenderName);
    dirtyFlag_[3] = true;
}
void Messages::setSenderName(std::string &&pSenderName) noexcept
{
    senderName_ = std::make_shared<std::string>(std::move(pSenderName));
    dirtyFlag_[3] = true;
}

const std::string &Messages::getValueOfSenderAvatar() const noexcept
{
    static const std::string defaultValue = std::string();
    if(senderAvatar_)
        return *senderAvatar_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Messages::getSenderAvatar() const noexcept
{
    return senderAvatar_;
}
void Messages::setSenderAvatar(const std::string &pSenderAvatar) noexcept
{
    senderAvatar_ = std::make_shared<std::string>(pSenderAvatar);
    dirtyFlag_[4] = true;
}
void Messages::setSenderAvatar(std::string &&pSenderAvatar) noexcept
{
    senderAvatar_ = std::make_shared<std::string>(std::move(pSenderAvatar));
    dirtyFlag_[4] = true;
}

const std::string &Messages::getValueOfContent() const noexcept
{
    static const std::string defaultValue = std::string();
    if(content_)
        return *content_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Messages::getContent() const noexcept
{
    return content_;
}
void Messages::setContent(const std::string &pContent) noexcept
{
    content_ = std::make_shared<std::string>(pContent);
    dirtyFlag_[5] = true;
}
void Messages::setContent(std::string &&pContent) noexcept
{
    content_ = std::make_shared<std::string>(std::move(pContent));
    dirtyFlag_[5] = true;
}
void Messages::setContentToNull() noexcept
{
    content_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Messages::getValueOfAttachment() const noexcept
{
    static const std::string defaultValue = std::string();
    if(attachment_)
        return *attachment_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Messages::getAttachment() const noexcept
{
    return attachment_;
}
void Messages::setAttachment(const std::string &pAttachment) noexcept
{
    attachment_ = std::make_shared<std::string>(pAttachment);
    dirtyFlag_[6] = true;
}
void Messages::setAttachment(std::string &&pAttachment) noexcept
{
    attachment_ = std::make_shared<std::string>(std::move(pAttachment));
    dirtyFlag_[6] = true;
}
void Messages::setAttachmentToNull() noexcept
{
    attachment_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Messages::getValueOfCreateTime() const noexcept
{
    static const std::string defaultValue = std::string();
    if(createTime_)
        return *createTime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Messages::getCreateTime() const noexcept
{
    return createTime_;
}
void Messages::setCreateTime(const std::string &pCreateTime) noexcept
{
    createTime_ = std::make_shared<std::string>(pCreateTime);
    dirtyFlag_[7] = true;
}
void Messages::setCreateTime(std::string &&pCreateTime) noexcept
{
    createTime_ = std::make_shared<std::string>(std::move(pCreateTime));
    dirtyFlag_[7] = true;
}
void Messages::setCreateTimeToNull() noexcept
{
    createTime_.reset();
    dirtyFlag_[7] = true;
}

const std::string &Messages::getValueOfUpdateTime() const noexcept
{
    static const std::string defaultValue = std::string();
    if(updateTime_)
        return *updateTime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Messages::getUpdateTime() const noexcept
{
    return updateTime_;
}
void Messages::setUpdateTime(const std::string &pUpdateTime) noexcept
{
    updateTime_ = std::make_shared<std::string>(pUpdateTime);
    dirtyFlag_[8] = true;
}
void Messages::setUpdateTime(std::string &&pUpdateTime) noexcept
{
    updateTime_ = std::make_shared<std::string>(std::move(pUpdateTime));
    dirtyFlag_[8] = true;
}
void Messages::setUpdateTimeToNull() noexcept
{
    updateTime_.reset();
    dirtyFlag_[8] = true;
}

void Messages::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Messages::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "message_id",
        "thread_id",
        "sender_uid",
        "sender_name",
        "sender_avatar",
        "content",
        "attachment",
        "create_time",
        "update_time"
    };
    return inCols;
}

void Messages::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getMessageId())
        {
            binder << getValueOfMessageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getThreadId())
        {
            binder << getValueOfThreadId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSenderUid())
        {
            binder << getValueOfSenderUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSenderName())
        {
            binder << getValueOfSenderName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSenderAvatar())
        {
            binder << getValueOfSenderAvatar();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getContent())
        {
            binder << getValueOfContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getAttachment())
        {
            binder << getValueOfAttachment();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreateTime())
        {
            binder << getValueOfCreateTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getUpdateTime())
        {
            binder << getValueOfUpdateTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Messages::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void Messages::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getMessageId())
        {
            binder << getValueOfMessageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getThreadId())
        {
            binder << getValueOfThreadId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSenderUid())
        {
            binder << getValueOfSenderUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSenderName())
        {
            binder << getValueOfSenderName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSenderAvatar())
        {
            binder << getValueOfSenderAvatar();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getContent())
        {
            binder << getValueOfContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getAttachment())
        {
            binder << getValueOfAttachment();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreateTime())
        {
            binder << getValueOfCreateTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getUpdateTime())
        {
            binder << getValueOfUpdateTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Messages::toJson() const
{
    Json::Value ret;
    if(getMessageId())
    {
        ret["message_id"]=(Json::Int64)getValueOfMessageId();
    }
    else
    {
        ret["message_id"]=Json::Value();
    }
    if(getThreadId())
    {
        ret["thread_id"]=(Json::Int64)getValueOfThreadId();
    }
    else
    {
        ret["thread_id"]=Json::Value();
    }
    if(getSenderUid())
    {
        ret["sender_uid"]=getValueOfSenderUid();
    }
    else
    {
        ret["sender_uid"]=Json::Value();
    }
    if(getSenderName())
    {
        ret["sender_name"]=getValueOfSenderName();
    }
    else
    {
        ret["sender_name"]=Json::Value();
    }
    if(getSenderAvatar())
    {
        ret["sender_avatar"]=getValueOfSenderAvatar();
    }
    else
    {
        ret["sender_avatar"]=Json::Value();
    }
    if(getContent())
    {
        ret["content"]=getValueOfContent();
    }
    else
    {
        ret["content"]=Json::Value();
    }
    if(getAttachment())
    {
        ret["attachment"]=getValueOfAttachment();
    }
    else
    {
        ret["attachment"]=Json::Value();
    }
    if(getCreateTime())
    {
        ret["create_time"]=getValueOfCreateTime();
    }
    else
    {
        ret["create_time"]=Json::Value();
    }
    if(getUpdateTime())
    {
        ret["update_time"]=getValueOfUpdateTime();
    }
    else
    {
        ret["update_time"]=Json::Value();
    }
    return ret;
}

Json::Value Messages::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getMessageId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfMessageId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getThreadId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfThreadId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getSenderUid())
            {
                ret[pMasqueradingVector[2]]=getValueOfSenderUid();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSenderName())
            {
                ret[pMasqueradingVector[3]]=getValueOfSenderName();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getSenderAvatar())
            {
                ret[pMasqueradingVector[4]]=getValueOfSenderAvatar();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getContent())
            {
                ret[pMasqueradingVector[5]]=getValueOfContent();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getAttachment())
            {
                ret[pMasqueradingVector[6]]=getValueOfAttachment();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCreateTime())
            {
                ret[pMasqueradingVector[7]]=getValueOfCreateTime();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getUpdateTime())
            {
                ret[pMasqueradingVector[8]]=getValueOfUpdateTime();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getMessageId())
    {
        ret["message_id"]=(Json::Int64)getValueOfMessageId();
    }
    else
    {
        ret["message_id"]=Json::Value();
    }
    if(getThreadId())
    {
        ret["thread_id"]=(Json::Int64)getValueOfThreadId();
    }
    else
    {
        ret["thread_id"]=Json::Value();
    }
    if(getSenderUid())
    {
        ret["sender_uid"]=getValueOfSenderUid();
    }
    else
    {
        ret["sender_uid"]=Json::Value();
    }
    if(getSenderName())
    {
        ret["sender_name"]=getValueOfSenderName();
    }
    else
    {
        ret["sender_name"]=Json::Value();
    }
    if(getSenderAvatar())
    {
        ret["sender_avatar"]=getValueOfSenderAvatar();
    }
    else
    {
        ret["sender_avatar"]=Json::Value();
    }
    if(getContent())
    {
        ret["content"]=getValueOfContent();
    }
    else
    {
        ret["content"]=Json::Value();
    }
    if(getAttachment())
    {
        ret["attachment"]=getValueOfAttachment();
    }
    else
    {
        ret["attachment"]=Json::Value();
    }
    if(getCreateTime())
    {
        ret["create_time"]=getValueOfCreateTime();
    }
    else
    {
        ret["create_time"]=Json::Value();
    }
    if(getUpdateTime())
    {
        ret["update_time"]=getValueOfUpdateTime();
    }
    else
    {
        ret["update_time"]=Json::Value();
    }
    return ret;
}

bool Messages::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("message_id"))
    {
        if(!validJsonOfField(0, "message_id", pJson["message_id"], err, true))
            return false;
    }
    if(pJson.isMember("thread_id"))
    {
        if(!validJsonOfField(1, "thread_id", pJson["thread_id"], err, true))
            return false;
    }
    else
    {
        err="The thread_id column cannot be null";
        return false;
    }
    if(pJson.isMember("sender_uid"))
    {
        if(!validJsonOfField(2, "sender_uid", pJson["sender_uid"], err, true))
            return false;
    }
    else
    {
        err="The sender_uid column cannot be null";
        return false;
    }
    if(pJson.isMember("sender_name"))
    {
        if(!validJsonOfField(3, "sender_name", pJson["sender_name"], err, true))
            return false;
    }
    else
    {
        err="The sender_name column cannot be null";
        return false;
    }
    if(pJson.isMember("sender_avatar"))
    {
        if(!validJsonOfField(4, "sender_avatar", pJson["sender_avatar"], err, true))
            return false;
    }
    else
    {
        err="The sender_avatar column cannot be null";
        return false;
    }
    if(pJson.isMember("content"))
    {
        if(!validJsonOfField(5, "content", pJson["content"], err, true))
            return false;
    }
    if(pJson.isMember("attachment"))
    {
        if(!validJsonOfField(6, "attachment", pJson["attachment"], err, true))
            return false;
    }
    if(pJson.isMember("create_time"))
    {
        if(!validJsonOfField(7, "create_time", pJson["create_time"], err, true))
            return false;
    }
    if(pJson.isMember("update_time"))
    {
        if(!validJsonOfField(8, "update_time", pJson["update_time"], err, true))
            return false;
    }
    return true;
}
bool Messages::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Messages::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("message_id"))
    {
        if(!validJsonOfField(0, "message_id", pJson["message_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("thread_id"))
    {
        if(!validJsonOfField(1, "thread_id", pJson["thread_id"], err, false))
            return false;
    }
    if(pJson.isMember("sender_uid"))
    {
        if(!validJsonOfField(2, "sender_uid", pJson["sender_uid"], err, false))
            return false;
    }
    if(pJson.isMember("sender_name"))
    {
        if(!validJsonOfField(3, "sender_name", pJson["sender_name"], err, false))
            return false;
    }
    if(pJson.isMember("sender_avatar"))
    {
        if(!validJsonOfField(4, "sender_avatar", pJson["sender_avatar"], err, false))
            return false;
    }
    if(pJson.isMember("content"))
    {
        if(!validJsonOfField(5, "content", pJson["content"], err, false))
            return false;
    }
    if(pJson.isMember("attachment"))
    {
        if(!validJsonOfField(6, "attachment", pJson["attachment"], err, false))
            return false;
    }
    if(pJson.isMember("create_time"))
    {
        if(!validJsonOfField(7, "create_time", pJson["create_time"], err, false))
            return false;
    }
    if(pJson.isMember("update_time"))
    {
        if(!validJsonOfField(8, "update_time", pJson["update_time"], err, false))
            return false;
    }
    return true;
}
bool Messages::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Messages::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
