/**
 *
 *  Notifications.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */
#include "pch.h"

#include "Notifications.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Notifications::primaryKeyName = "";
const bool Notifications::hasPrimaryKey = false;
const std::string Notifications::tableName = "notifications";

const std::vector<typename Notifications::MetaData> Notifications::metaData_={
};
const std::string &Notifications::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Notifications::Notifications(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 0 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
    }

}

Notifications::Notifications(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

Notifications::Notifications(const Json::Value &pJson) noexcept(false)
{
}

void Notifications::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

void Notifications::updateByJson(const Json::Value &pJson) noexcept(false)
{
}

void Notifications::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Notifications::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
    };
    return inCols;
}

void Notifications::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
}

const std::vector<std::string> Notifications::updateColumns() const
{
    std::vector<std::string> ret;
    return ret;
}

void Notifications::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
}
Json::Value Notifications::toJson() const
{
    Json::Value ret;
    return ret;
}

Json::Value Notifications::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 0)
    {
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    return ret;
}

bool Notifications::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Notifications::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Notifications::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Notifications::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Notifications::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson,
                                     std::string &err,
                                     bool isForCreation)
{
    switch(index)
    {
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
