/**
 *
 *  Notifications.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */
#include "pch.h"
#include "Notifications.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Notifications::Cols::_id = "id";
const std::string Notifications::Cols::_notification_id = "notification_id";
const std::string Notifications::Cols::_notification_type = "notification_type";
const std::string Notifications::Cols::_sender_uid = "sender_uid";
const std::string Notifications::Cols::_receiver_uid = "receiver_uid";
const std::string Notifications::Cols::_content = "content";
const std::string Notifications::Cols::_is_read = "is_read";
const std::string Notifications::Cols::_create_time = "create_time";
const std::string Notifications::primaryKeyName = "id";
const bool Notifications::hasPrimaryKey = true;
const std::string Notifications::tableName = "notifications";

const std::vector<typename Notifications::MetaData> Notifications::metaData_={
{"id","int64_t","integer",8,1,1,0},
{"notification_id","std::string","text",0,0,0,1},
{"notification_type","std::string","text",0,0,0,1},
{"sender_uid","std::string","text",0,0,0,1},
{"receiver_uid","std::string","text",0,0,0,1},
{"content","std::string","text",0,0,0,0},
{"is_read","std::string","boolean",0,0,0,0},
{"create_time","std::string","",0,0,0,0}
};
const std::string &Notifications::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Notifications::Notifications(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["notification_id"].isNull())
        {
            notificationId_=std::make_shared<std::string>(r["notification_id"].as<std::string>());
        }
        if(!r["notification_type"].isNull())
        {
            notificationType_=std::make_shared<std::string>(r["notification_type"].as<std::string>());
        }
        if(!r["sender_uid"].isNull())
        {
            senderUid_=std::make_shared<std::string>(r["sender_uid"].as<std::string>());
        }
        if(!r["receiver_uid"].isNull())
        {
            receiverUid_=std::make_shared<std::string>(r["receiver_uid"].as<std::string>());
        }
        if(!r["content"].isNull())
        {
            content_=std::make_shared<std::string>(r["content"].as<std::string>());
        }
        if(!r["is_read"].isNull())
        {
            isRead_=std::make_shared<std::string>(r["is_read"].as<std::string>());
        }
        if(!r["create_time"].isNull())
        {
            createTime_=std::make_shared<std::string>(r["create_time"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            notificationId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            notificationType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            senderUid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            receiverUid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            content_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            isRead_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            createTime_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Notifications::Notifications(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            notificationId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            notificationType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            senderUid_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            receiverUid_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            content_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            isRead_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            createTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
}

Notifications::Notifications(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("notification_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["notification_id"].isNull())
        {
            notificationId_=std::make_shared<std::string>(pJson["notification_id"].asString());
        }
    }
    if(pJson.isMember("notification_type"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["notification_type"].isNull())
        {
            notificationType_=std::make_shared<std::string>(pJson["notification_type"].asString());
        }
    }
    if(pJson.isMember("sender_uid"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["sender_uid"].isNull())
        {
            senderUid_=std::make_shared<std::string>(pJson["sender_uid"].asString());
        }
    }
    if(pJson.isMember("receiver_uid"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["receiver_uid"].isNull())
        {
            receiverUid_=std::make_shared<std::string>(pJson["receiver_uid"].asString());
        }
    }
    if(pJson.isMember("content"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["content"].isNull())
        {
            content_=std::make_shared<std::string>(pJson["content"].asString());
        }
    }
    if(pJson.isMember("is_read"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["is_read"].isNull())
        {
            isRead_=std::make_shared<std::string>(pJson["is_read"].asString());
        }
    }
    if(pJson.isMember("create_time"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["create_time"].isNull())
        {
            createTime_=std::make_shared<std::string>(pJson["create_time"].asString());
        }
    }
}

void Notifications::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            notificationId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            notificationType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            senderUid_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            receiverUid_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            content_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            isRead_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            createTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
}

void Notifications::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("notification_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["notification_id"].isNull())
        {
            notificationId_=std::make_shared<std::string>(pJson["notification_id"].asString());
        }
    }
    if(pJson.isMember("notification_type"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["notification_type"].isNull())
        {
            notificationType_=std::make_shared<std::string>(pJson["notification_type"].asString());
        }
    }
    if(pJson.isMember("sender_uid"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["sender_uid"].isNull())
        {
            senderUid_=std::make_shared<std::string>(pJson["sender_uid"].asString());
        }
    }
    if(pJson.isMember("receiver_uid"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["receiver_uid"].isNull())
        {
            receiverUid_=std::make_shared<std::string>(pJson["receiver_uid"].asString());
        }
    }
    if(pJson.isMember("content"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["content"].isNull())
        {
            content_=std::make_shared<std::string>(pJson["content"].asString());
        }
    }
    if(pJson.isMember("is_read"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["is_read"].isNull())
        {
            isRead_=std::make_shared<std::string>(pJson["is_read"].asString());
        }
    }
    if(pJson.isMember("create_time"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["create_time"].isNull())
        {
            createTime_=std::make_shared<std::string>(pJson["create_time"].asString());
        }
    }
}

const int64_t &Notifications::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Notifications::getId() const noexcept
{
    return id_;
}
void Notifications::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
void Notifications::setIdToNull() noexcept
{
    id_.reset();
    dirtyFlag_[0] = true;
}
const typename Notifications::PrimaryKeyType & Notifications::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Notifications::getValueOfNotificationId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(notificationId_)
        return *notificationId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Notifications::getNotificationId() const noexcept
{
    return notificationId_;
}
void Notifications::setNotificationId(const std::string &pNotificationId) noexcept
{
    notificationId_ = std::make_shared<std::string>(pNotificationId);
    dirtyFlag_[1] = true;
}
void Notifications::setNotificationId(std::string &&pNotificationId) noexcept
{
    notificationId_ = std::make_shared<std::string>(std::move(pNotificationId));
    dirtyFlag_[1] = true;
}

const std::string &Notifications::getValueOfNotificationType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(notificationType_)
        return *notificationType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Notifications::getNotificationType() const noexcept
{
    return notificationType_;
}
void Notifications::setNotificationType(const std::string &pNotificationType) noexcept
{
    notificationType_ = std::make_shared<std::string>(pNotificationType);
    dirtyFlag_[2] = true;
}
void Notifications::setNotificationType(std::string &&pNotificationType) noexcept
{
    notificationType_ = std::make_shared<std::string>(std::move(pNotificationType));
    dirtyFlag_[2] = true;
}

const std::string &Notifications::getValueOfSenderUid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(senderUid_)
        return *senderUid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Notifications::getSenderUid() const noexcept
{
    return senderUid_;
}
void Notifications::setSenderUid(const std::string &pSenderUid) noexcept
{
    senderUid_ = std::make_shared<std::string>(pSenderUid);
    dirtyFlag_[3] = true;
}
void Notifications::setSenderUid(std::string &&pSenderUid) noexcept
{
    senderUid_ = std::make_shared<std::string>(std::move(pSenderUid));
    dirtyFlag_[3] = true;
}

const std::string &Notifications::getValueOfReceiverUid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(receiverUid_)
        return *receiverUid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Notifications::getReceiverUid() const noexcept
{
    return receiverUid_;
}
void Notifications::setReceiverUid(const std::string &pReceiverUid) noexcept
{
    receiverUid_ = std::make_shared<std::string>(pReceiverUid);
    dirtyFlag_[4] = true;
}
void Notifications::setReceiverUid(std::string &&pReceiverUid) noexcept
{
    receiverUid_ = std::make_shared<std::string>(std::move(pReceiverUid));
    dirtyFlag_[4] = true;
}

const std::string &Notifications::getValueOfContent() const noexcept
{
    static const std::string defaultValue = std::string();
    if(content_)
        return *content_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Notifications::getContent() const noexcept
{
    return content_;
}
void Notifications::setContent(const std::string &pContent) noexcept
{
    content_ = std::make_shared<std::string>(pContent);
    dirtyFlag_[5] = true;
}
void Notifications::setContent(std::string &&pContent) noexcept
{
    content_ = std::make_shared<std::string>(std::move(pContent));
    dirtyFlag_[5] = true;
}
void Notifications::setContentToNull() noexcept
{
    content_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Notifications::getValueOfIsRead() const noexcept
{
    static const std::string defaultValue = std::string();
    if(isRead_)
        return *isRead_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Notifications::getIsRead() const noexcept
{
    return isRead_;
}
void Notifications::setIsRead(const std::string &pIsRead) noexcept
{
    isRead_ = std::make_shared<std::string>(pIsRead);
    dirtyFlag_[6] = true;
}
void Notifications::setIsRead(std::string &&pIsRead) noexcept
{
    isRead_ = std::make_shared<std::string>(std::move(pIsRead));
    dirtyFlag_[6] = true;
}
void Notifications::setIsReadToNull() noexcept
{
    isRead_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Notifications::getValueOfCreateTime() const noexcept
{
    static const std::string defaultValue = std::string();
    if(createTime_)
        return *createTime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Notifications::getCreateTime() const noexcept
{
    return createTime_;
}
void Notifications::setCreateTime(const std::string &pCreateTime) noexcept
{
    createTime_ = std::make_shared<std::string>(pCreateTime);
    dirtyFlag_[7] = true;
}
void Notifications::setCreateTime(std::string &&pCreateTime) noexcept
{
    createTime_ = std::make_shared<std::string>(std::move(pCreateTime));
    dirtyFlag_[7] = true;
}
void Notifications::setCreateTimeToNull() noexcept
{
    createTime_.reset();
    dirtyFlag_[7] = true;
}

void Notifications::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &Notifications::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "notification_id",
        "notification_type",
        "sender_uid",
        "receiver_uid",
        "content",
        "is_read",
        "create_time"
    };
    return inCols;
}

void Notifications::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getNotificationId())
        {
            binder << getValueOfNotificationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNotificationType())
        {
            binder << getValueOfNotificationType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSenderUid())
        {
            binder << getValueOfSenderUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getReceiverUid())
        {
            binder << getValueOfReceiverUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getContent())
        {
            binder << getValueOfContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getIsRead())
        {
            binder << getValueOfIsRead();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreateTime())
        {
            binder << getValueOfCreateTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Notifications::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void Notifications::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getNotificationId())
        {
            binder << getValueOfNotificationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNotificationType())
        {
            binder << getValueOfNotificationType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSenderUid())
        {
            binder << getValueOfSenderUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getReceiverUid())
        {
            binder << getValueOfReceiverUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getContent())
        {
            binder << getValueOfContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getIsRead())
        {
            binder << getValueOfIsRead();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreateTime())
        {
            binder << getValueOfCreateTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Notifications::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getNotificationId())
    {
        ret["notification_id"]=getValueOfNotificationId();
    }
    else
    {
        ret["notification_id"]=Json::Value();
    }
    if(getNotificationType())
    {
        ret["notification_type"]=getValueOfNotificationType();
    }
    else
    {
        ret["notification_type"]=Json::Value();
    }
    if(getSenderUid())
    {
        ret["sender_uid"]=getValueOfSenderUid();
    }
    else
    {
        ret["sender_uid"]=Json::Value();
    }
    if(getReceiverUid())
    {
        ret["receiver_uid"]=getValueOfReceiverUid();
    }
    else
    {
        ret["receiver_uid"]=Json::Value();
    }
    if(getContent())
    {
        ret["content"]=getValueOfContent();
    }
    else
    {
        ret["content"]=Json::Value();
    }
    if(getIsRead())
    {
        ret["is_read"]=getValueOfIsRead();
    }
    else
    {
        ret["is_read"]=Json::Value();
    }
    if(getCreateTime())
    {
        ret["create_time"]=getValueOfCreateTime();
    }
    else
    {
        ret["create_time"]=Json::Value();
    }
    return ret;
}

Json::Value Notifications::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getNotificationId())
            {
                ret[pMasqueradingVector[1]]=getValueOfNotificationId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getNotificationType())
            {
                ret[pMasqueradingVector[2]]=getValueOfNotificationType();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSenderUid())
            {
                ret[pMasqueradingVector[3]]=getValueOfSenderUid();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getReceiverUid())
            {
                ret[pMasqueradingVector[4]]=getValueOfReceiverUid();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getContent())
            {
                ret[pMasqueradingVector[5]]=getValueOfContent();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getIsRead())
            {
                ret[pMasqueradingVector[6]]=getValueOfIsRead();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCreateTime())
            {
                ret[pMasqueradingVector[7]]=getValueOfCreateTime();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getNotificationId())
    {
        ret["notification_id"]=getValueOfNotificationId();
    }
    else
    {
        ret["notification_id"]=Json::Value();
    }
    if(getNotificationType())
    {
        ret["notification_type"]=getValueOfNotificationType();
    }
    else
    {
        ret["notification_type"]=Json::Value();
    }
    if(getSenderUid())
    {
        ret["sender_uid"]=getValueOfSenderUid();
    }
    else
    {
        ret["sender_uid"]=Json::Value();
    }
    if(getReceiverUid())
    {
        ret["receiver_uid"]=getValueOfReceiverUid();
    }
    else
    {
        ret["receiver_uid"]=Json::Value();
    }
    if(getContent())
    {
        ret["content"]=getValueOfContent();
    }
    else
    {
        ret["content"]=Json::Value();
    }
    if(getIsRead())
    {
        ret["is_read"]=getValueOfIsRead();
    }
    else
    {
        ret["is_read"]=Json::Value();
    }
    if(getCreateTime())
    {
        ret["create_time"]=getValueOfCreateTime();
    }
    else
    {
        ret["create_time"]=Json::Value();
    }
    return ret;
}

bool Notifications::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("notification_id"))
    {
        if(!validJsonOfField(1, "notification_id", pJson["notification_id"], err, true))
            return false;
    }
    else
    {
        err="The notification_id column cannot be null";
        return false;
    }
    if(pJson.isMember("notification_type"))
    {
        if(!validJsonOfField(2, "notification_type", pJson["notification_type"], err, true))
            return false;
    }
    else
    {
        err="The notification_type column cannot be null";
        return false;
    }
    if(pJson.isMember("sender_uid"))
    {
        if(!validJsonOfField(3, "sender_uid", pJson["sender_uid"], err, true))
            return false;
    }
    else
    {
        err="The sender_uid column cannot be null";
        return false;
    }
    if(pJson.isMember("receiver_uid"))
    {
        if(!validJsonOfField(4, "receiver_uid", pJson["receiver_uid"], err, true))
            return false;
    }
    else
    {
        err="The receiver_uid column cannot be null";
        return false;
    }
    if(pJson.isMember("content"))
    {
        if(!validJsonOfField(5, "content", pJson["content"], err, true))
            return false;
    }
    if(pJson.isMember("is_read"))
    {
        if(!validJsonOfField(6, "is_read", pJson["is_read"], err, true))
            return false;
    }
    if(pJson.isMember("create_time"))
    {
        if(!validJsonOfField(7, "create_time", pJson["create_time"], err, true))
            return false;
    }
    return true;
}
bool Notifications::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Notifications::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("notification_id"))
    {
        if(!validJsonOfField(1, "notification_id", pJson["notification_id"], err, false))
            return false;
    }
    if(pJson.isMember("notification_type"))
    {
        if(!validJsonOfField(2, "notification_type", pJson["notification_type"], err, false))
            return false;
    }
    if(pJson.isMember("sender_uid"))
    {
        if(!validJsonOfField(3, "sender_uid", pJson["sender_uid"], err, false))
            return false;
    }
    if(pJson.isMember("receiver_uid"))
    {
        if(!validJsonOfField(4, "receiver_uid", pJson["receiver_uid"], err, false))
            return false;
    }
    if(pJson.isMember("content"))
    {
        if(!validJsonOfField(5, "content", pJson["content"], err, false))
            return false;
    }
    if(pJson.isMember("is_read"))
    {
        if(!validJsonOfField(6, "is_read", pJson["is_read"], err, false))
            return false;
    }
    if(pJson.isMember("create_time"))
    {
        if(!validJsonOfField(7, "create_time", pJson["create_time"], err, false))
            return false;
    }
    return true;
}
bool Notifications::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Notifications::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson,
                                     std::string &err,
                                     bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
