/**
 *
 *  PrivateChats.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */
#include "pch.h"

#include "PrivateChats.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::postgres;

const std::string PrivateChats::Cols::_thread_id = "\"thread_id\"";
const std::string PrivateChats::Cols::_uid1 = "\"uid1\"";
const std::string PrivateChats::Cols::_uid2 = "\"uid2\"";
const std::string PrivateChats::primaryKeyName = "";
const bool PrivateChats::hasPrimaryKey = false;
const std::string PrivateChats::tableName = "\"private_chats\"";

const std::vector<typename PrivateChats::MetaData> PrivateChats::metaData_={
{"thread_id","int64_t","bigint",8,0,0,1},
{"uid1","std::string","text",0,0,0,1},
{"uid2","std::string","text",0,0,0,1}
};
const std::string &PrivateChats::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PrivateChats::PrivateChats(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["thread_id"].isNull())
        {
            threadId_=std::make_shared<int64_t>(r["thread_id"].as<int64_t>());
        }
        if(!r["uid1"].isNull())
        {
            uid1_=std::make_shared<std::string>(r["uid1"].as<std::string>());
        }
        if(!r["uid2"].isNull())
        {
            uid2_=std::make_shared<std::string>(r["uid2"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            threadId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            uid1_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            uid2_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

PrivateChats::PrivateChats(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            threadId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uid1_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            uid2_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

PrivateChats::PrivateChats(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("thread_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["thread_id"].isNull())
        {
            threadId_=std::make_shared<int64_t>((int64_t)pJson["thread_id"].asInt64());
        }
    }
    if(pJson.isMember("uid1"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["uid1"].isNull())
        {
            uid1_=std::make_shared<std::string>(pJson["uid1"].asString());
        }
    }
    if(pJson.isMember("uid2"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["uid2"].isNull())
        {
            uid2_=std::make_shared<std::string>(pJson["uid2"].asString());
        }
    }
}

void PrivateChats::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            threadId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uid1_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            uid2_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

void PrivateChats::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("thread_id"))
    {
        dirtyFlag_[0] = true;
        if(!pJson["thread_id"].isNull())
        {
            threadId_=std::make_shared<int64_t>((int64_t)pJson["thread_id"].asInt64());
        }
    }
    if(pJson.isMember("uid1"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["uid1"].isNull())
        {
            uid1_=std::make_shared<std::string>(pJson["uid1"].asString());
        }
    }
    if(pJson.isMember("uid2"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["uid2"].isNull())
        {
            uid2_=std::make_shared<std::string>(pJson["uid2"].asString());
        }
    }
}

const int64_t &PrivateChats::getValueOfThreadId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(threadId_)
        return *threadId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PrivateChats::getThreadId() const noexcept
{
    return threadId_;
}
void PrivateChats::setThreadId(const int64_t &pThreadId) noexcept
{
    threadId_ = std::make_shared<int64_t>(pThreadId);
    dirtyFlag_[0] = true;
}

const std::string &PrivateChats::getValueOfUid1() const noexcept
{
    static const std::string defaultValue = std::string();
    if(uid1_)
        return *uid1_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PrivateChats::getUid1() const noexcept
{
    return uid1_;
}
void PrivateChats::setUid1(const std::string &pUid1) noexcept
{
    uid1_ = std::make_shared<std::string>(pUid1);
    dirtyFlag_[1] = true;
}
void PrivateChats::setUid1(std::string &&pUid1) noexcept
{
    uid1_ = std::make_shared<std::string>(std::move(pUid1));
    dirtyFlag_[1] = true;
}

const std::string &PrivateChats::getValueOfUid2() const noexcept
{
    static const std::string defaultValue = std::string();
    if(uid2_)
        return *uid2_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PrivateChats::getUid2() const noexcept
{
    return uid2_;
}
void PrivateChats::setUid2(const std::string &pUid2) noexcept
{
    uid2_ = std::make_shared<std::string>(pUid2);
    dirtyFlag_[2] = true;
}
void PrivateChats::setUid2(std::string &&pUid2) noexcept
{
    uid2_ = std::make_shared<std::string>(std::move(pUid2));
    dirtyFlag_[2] = true;
}

void PrivateChats::updateId(const uint64_t id)
{
}

const std::vector<std::string> &PrivateChats::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "thread_id",
        "uid1",
        "uid2"
    };
    return inCols;
}

void PrivateChats::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getThreadId())
        {
            binder << getValueOfThreadId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUid1())
        {
            binder << getValueOfUid1();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUid2())
        {
            binder << getValueOfUid2();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PrivateChats::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void PrivateChats::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getThreadId())
        {
            binder << getValueOfThreadId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUid1())
        {
            binder << getValueOfUid1();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUid2())
        {
            binder << getValueOfUid2();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PrivateChats::toJson() const
{
    Json::Value ret;
    if(getThreadId())
    {
        ret["thread_id"]=(Json::Int64)getValueOfThreadId();
    }
    else
    {
        ret["thread_id"]=Json::Value();
    }
    if(getUid1())
    {
        ret["uid1"]=getValueOfUid1();
    }
    else
    {
        ret["uid1"]=Json::Value();
    }
    if(getUid2())
    {
        ret["uid2"]=getValueOfUid2();
    }
    else
    {
        ret["uid2"]=Json::Value();
    }
    return ret;
}

Json::Value PrivateChats::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getThreadId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfThreadId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUid1())
            {
                ret[pMasqueradingVector[1]]=getValueOfUid1();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUid2())
            {
                ret[pMasqueradingVector[2]]=getValueOfUid2();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getThreadId())
    {
        ret["thread_id"]=(Json::Int64)getValueOfThreadId();
    }
    else
    {
        ret["thread_id"]=Json::Value();
    }
    if(getUid1())
    {
        ret["uid1"]=getValueOfUid1();
    }
    else
    {
        ret["uid1"]=Json::Value();
    }
    if(getUid2())
    {
        ret["uid2"]=getValueOfUid2();
    }
    else
    {
        ret["uid2"]=Json::Value();
    }
    return ret;
}

bool PrivateChats::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("thread_id"))
    {
        if(!validJsonOfField(0, "thread_id", pJson["thread_id"], err, true))
            return false;
    }
    else
    {
        err="The thread_id column cannot be null";
        return false;
    }
    if(pJson.isMember("uid1"))
    {
        if(!validJsonOfField(1, "uid1", pJson["uid1"], err, true))
            return false;
    }
    else
    {
        err="The uid1 column cannot be null";
        return false;
    }
    if(pJson.isMember("uid2"))
    {
        if(!validJsonOfField(2, "uid2", pJson["uid2"], err, true))
            return false;
    }
    else
    {
        err="The uid2 column cannot be null";
        return false;
    }
    return true;
}
bool PrivateChats::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PrivateChats::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("thread_id"))
    {
        if(!validJsonOfField(0, "thread_id", pJson["thread_id"], err, false))
            return false;
    }
    if(pJson.isMember("uid1"))
    {
        if(!validJsonOfField(1, "uid1", pJson["uid1"], err, false))
            return false;
    }
    if(pJson.isMember("uid2"))
    {
        if(!validJsonOfField(2, "uid2", pJson["uid2"], err, false))
            return false;
    }
    return true;
}
bool PrivateChats::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PrivateChats::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
